services:
  phishing_api:
    image: visual_phish_detector:latest
    build: .
    
    container_name: visual_phish_detector
    restart: always
    ports:
      - "8000:8000"
    
    environment:
      - PYTHONUNBUFFERED=1
      - USE_NNPACK=0
      - MAX_CONCURRENT_SCANS=4
      - MAX_SCAN_QUEUE_SIZE=20

    ## uncomment to run on GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]